import {useEffect,useRef,useState} from 'react';
import {ask,listen,type AskResponse,type Citation,healthz} from './api';
import {PcmRecorder} from './recorder';
import Mascot,{type NovaState} from './Mascot';
import LatencyHUD from './Latency';
import './app.css';

type Message={id:string;role:'user'|'assistant';text:string;response?:AskResponse};type Conversation={id:string;title:string;messages:Message[]};
const refusalText=(c:string|null)=>({NO_SPEECH:"I didn't hear anything. Try speaking again.",UNINTELLIGIBLE_AUDIO:"I couldn't understand the audio. Please try again.",OUT_OF_SCOPE:"I couldn't find enough relevant information in my sources to answer that.",LOW_CONFIDENCE:"I don't have enough confidence in the retrieved information to answer that reliably.",INJECTION_DETECTED:"I can't follow that instruction.",UNSUPPORTED_LANGUAGE:"I can't process that language yet.",UNSAFE_INPUT:"I can't help with that request.",UNGROUNDED_ANSWER:"I couldn't verify the generated answer against the retrieved sources.",MALFORMED_QUERY:"I couldn't understand the question.",BUDGET_EXCEEDED:"That request took too long to complete. Please try again.",INTERNAL_ERROR:"Voice transcription failed. Check that SARVAM_API_KEY is configured."}[c||'']||"I couldn't answer that right now.");
function App(){const [convos,setConvos]=useState<Conversation[]>([]);const [active,setActive]=useState('');const [state,setState]=useState<NovaState>('idle');const [text,setText]=useState('');const [error,setError]=useState('');const recorder=useRef<PcmRecorder|null>(null);const speaking=useRef(0);
 useEffect(()=>{const saved=localStorage.getItem('nova-conversations');if(saved){try{const x=JSON.parse(saved);setConvos(x);if(x[0])setActive(x[0].id)}catch{}}healthz().catch(()=>{});return()=>speechSynthesis.cancel()},[]);
 useEffect(()=>{localStorage.setItem('nova-conversations',JSON.stringify(convos.filter(c=>c.messages.length>0)))},[convos]);
 const current=convos.find(c=>c.id===active);const newConversation=()=>{const c={id:crypto.randomUUID(),title:'New Conversation',messages:[]};setConvos(v=>[c,...v]);setActive(c.id);setText('');setError('');speechSynthesis.cancel();setState('idle')};
 const ensureConversation=()=>{if(active&&current)return active;const id=crypto.randomUUID();setConvos(v=>[{id,title:'New Conversation',messages:[]},...v]);setActive(id);return id};
 const add=async(q:string,voice=false)=>{q=q.trim();if(!q)return;const id=ensureConversation();const uid=crypto.randomUUID(),aid=crypto.randomUUID();setConvos(v=>v.map(c=>c.id===id?{...c,title:c.messages.length?c.title:(q.length>42?q.slice(0,42)+'…':q),messages:[...c.messages,{id:uid,role:'user',text:q},{id:aid,role:'assistant',text:'',response:undefined}]}:c));setText('');setError('');setState(voice?'processing':'processing');try{const r=voice?await listen((window as any).__novaAudio):await ask(q);setConvos(v=>v.map(c=>c.id===id?{...c,messages:c.messages.map(m=>m.id===aid?{...m,text:r.verdict==='ANSWERED'&&r.answer?r.answer.text:refusalText(r.refusal_code),response:r}:m)}:c));if(r.verdict==='ANSWERED'&&r.answer){speak(r.answer.text);setState('speaking')}else setState('error')}catch(e){setError(e instanceof Error?e.message:'Request failed');setConvos(v=>v.map(c=>c.id===id?{...c,messages:c.messages.map(m=>m.id===aid?{...m,text:'I couldn’t reach NOVA’s backend. Please check that the FastAPI server is running.',}:m)}:c));setState('error')}finally{(window as any).__novaAudio=null}};
 const submit=()=>add(text);const speak=(s:string)=>{speechSynthesis.cancel();const token=++speaking.current;const u=new SpeechSynthesisUtterance(s);u.lang='en-IN';u.rate=1;u.pitch=1.05;u.onend=()=>{if(token===speaking.current)setState('idle')};u.onerror=()=>{if(token===speaking.current)setState('idle')};speechSynthesis.speak(u)};
 const startMic=async()=>{if(state==='listening')return;speechSynthesis.cancel();setError('');try{recorder.current=new PcmRecorder();await recorder.current.start();setState('listening')}catch(e){setError(e instanceof Error?e.message:'Microphone permission was denied');setState('error')}};
 const stopMic=async()=>{if(state!=='listening'||!recorder.current)return;try{setState('processing');const wav=await recorder.current.stop();(window as any).__novaAudio=wav;const id=ensureConversation();const q='Voice question';// actual transcript is supplied by backend; placeholder is replaced below
 const r=await listen(wav);setConvos(v=>v.map(c=>c.id===id?{...c,title:c.messages.length?c.title:'Voice conversation',messages:[...c.messages,{id:crypto.randomUUID(),role:'user',text:r.transcript?.text||q},{id:crypto.randomUUID(),role:'assistant',text:r.verdict==='ANSWERED'&&r.answer?r.answer.text:refusalText(r.refusal_code),response:r}]}:c));if(r.verdict==='ANSWERED'&&r.answer){speak(r.answer.text);setState('speaking')}else setState('error')}catch(e){setError(e instanceof Error?e.message:'Voice request failed');setState('error')}finally{recorder.current=null;(window as any).__novaAudio=null}};
 const onKey=(e:React.KeyboardEvent)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}};
 return <div className="nova-app"><aside className="sidebar"><div className="side-head"><div className="brand">NOVA <span></span></div><button className="close" onClick={()=>document.body.classList.toggle('side-hidden')}>×</button></div><button className="new" onClick={newConversation}>＋ New Conversation</button><div className="recent">RECENT CHATS</div><div className="history">{convos.map(c=><div key={c.id} className={'history-row'+(c.id===active?' active':'')}><button className="history" onClick={()=>{setActive(c.id);setText('');setError('');speechSynthesis.cancel();setState('idle')}}>{c.title}</button>{c.id===active&&<button className="hist-del" title="Delete chat" onClick={()=>{setConvos(v=>v.filter(x=>x.id!==c.id));if(active===c.id){setActive('');setText('');setError('');}}}>×</button>}</div>)}</div></aside><main className="workspace"><button className="menu" onClick={()=>document.body.classList.toggle('side-hidden')}>☰</button><section className="mascot-panel"><Mascot state={state}/><div className="nova-status">{state==='listening'?'Listening…':state==='processing'?'Processing…':state==='speaking'?'Speaking…':state==='error'?'Something went wrong':' '}</div><button className={state==='listening'?'mic active':'mic'} onPointerDown={startMic} onPointerUp={stopMic} onPointerCancel={stopMic} aria-label="Talk to Nova">◉</button><div className="mic-tip">Hold to talk with NOVA</div></section><section className="chat"><div className="messages">{!current||current.messages.length===0?<div className="empty"><h1>Talk to Nova</h1><p>Ask a question by typing or holding the microphone.</p></div>:current.messages.map(m=><Message key={m.id} m={m}/>)}</div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={onKey} placeholder="Message NOVA…" rows={1}/><button className="send" onClick={submit} disabled={!text.trim()||state==='processing'||state==='listening'}>↑</button></div>{error&&<div className="error">{error}</div>}</section></main></div>}
function Message({m}:{m:Message}){return <div className={'message '+m.role}><div className="bubble">{m.text||'…'}</div>{m.role==='assistant'&&m.response&&<Sources citations={m.response.citations}/>}{m.role==='assistant'&&m.response&&Object.keys(m.response.timings_ms||{}).length>0&&<LatencyHUD timings={m.response.timings_ms}/>}</div>}
function Sources({citations}:{citations:Citation[]}){if(!citations.length)return null;return <details className="sources"><summary>Sources · {citations.length}</summary>{citations.map((c,i)=><div key={i} className="source"><span>{c.strategy}</span><code>{c.chunk_id}</code><small>score {c.score.toFixed(3)}</small></div>)}</details>}
export default App;
