import {useEffect,useRef} from 'react';
import * as THREE from 'three';
export type NovaState='idle'|'listening'|'processing'|'speaking'|'error';
export default function Mascot({state}:{state:NovaState}){
 const mount=useRef<HTMLDivElement>(null); const stateRef=useRef(state); stateRef.current=state;
 useEffect(()=>{const stage=mount.current!; const scene=new THREE.Scene(); scene.background=new THREE.Color(0xF7F1EA); const camera=new THREE.PerspectiveCamera(32,stage.clientWidth/stage.clientHeight,.1,100);camera.position.set(0,.2,8.5); const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(stage.clientWidth,stage.clientHeight);stage.appendChild(renderer.domElement);
 scene.add(new THREE.AmbientLight(0xffffff,.8));const key=new THREE.DirectionalLight(0xfff2e0,1);key.position.set(3,4,5);scene.add(key);
 const BODY=0xF6E3D3,BEANIE=0xE8A87C,POM=0xF3B8B8,CHEEK=0xF4A6A6,INK=0x4A3428; const box=(w:number,h:number,d:number,color:number,opts:any={})=>new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.75,...opts}));
 const root=new THREE.Group();scene.add(root);const tilt=new THREE.Group();root.add(tilt);const breathe=new THREE.Group();tilt.add(breathe);breathe.add(box(2,1.7,1.5,BODY));const armL=box(.32,.55,.32,BODY);armL.position.set(-1.15,-.1,0);breathe.add(armL);const armR=box(.32,.55,.32,BODY);armR.position.set(1.15,-.1,0);breathe.add(armR);const footL=box(.4,.3,.42,BODY);footL.position.set(-.55,-1.02,.25);breathe.add(footL);const footR=box(.4,.3,.42,BODY);footR.position.set(.55,-1.02,.25);breathe.add(footR);const band=box(2.05,.22,1.75,BEANIE);band.position.set(0,1.05,0);breathe.add(band);const beanie=new THREE.Mesh(new THREE.ConeGeometry(.95,.55,4),new THREE.MeshStandardMaterial({color:BEANIE}));beanie.rotation.y=Math.PI/4;beanie.position.set(0,1.35,-.05);breathe.add(beanie);const pomGroup=new THREE.Group();const pom=new THREE.Mesh(new THREE.IcosahedronGeometry(.18,0),new THREE.MeshStandardMaterial({color:POM,roughness:.9}));pom.position.set(0,1.75,-.05);pomGroup.add(pom);breathe.add(pomGroup);
 const cheek=(x:number)=>{const c=box(.22,.16,.02,CHEEK,{roughness:1});c.position.set(x,-.15,.76);return c};breathe.add(cheek(-.62),cheek(.62));const eye=(x:number)=>{const e=box(.16,.16,.02,INK);e.position.set(x,.18,.76);return e};const eyeL=eye(-.35),eyeR=eye(.35);breathe.add(eyeL,eyeR);const brow=(x:number)=>{const b=box(.2,.05,.02,INK,{roughness:1});b.position.set(x,.42,.76);return b};const browL=brow(-.35),browR=brow(.35);breathe.add(browL,browR);const mouth=box(.28,.06,.02,INK);mouth.position.set(0,-.15,.76);breathe.add(mouth);const moteGroup=new THREE.Group();moteGroup.position.set(0,2.1,0);const mote1=box(.09,.09,.09,0xFFE79A,{emissive:0xFFE79A,emissiveIntensity:.5}),mote2=box(.065,.065,.065,0xFFE79A,{emissive:0xFFE79A,emissiveIntensity:.5});mote1.position.set(.5,0,0);mote2.position.set(-.4,.15,.2);moteGroup.add(mote1,mote2);moteGroup.visible=false;breathe.add(moteGroup);
 const mouse={x:0,y:0,tx:0,ty:0};const onMouse=(e:MouseEvent)=>{mouse.tx=e.clientX/innerWidth*2-1;mouse.ty=-(e.clientY/innerHeight)*2+1};window.addEventListener('mousemove',onMouse);const clock=new THREE.Clock();let nextBlink=2+Math.random()*2,blink=-1;const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
 let raf=0;const animate=()=>{raf=requestAnimationFrame(animate);const dt=clock.getDelta(),t=clock.getElapsedTime(),s=stateRef.current;mouse.x=lerp(mouse.x,mouse.tx,.1);mouse.y=lerp(mouse.y,mouse.ty,.1);const bobSpeed=s==='speaking'?5:2;tilt.position.y=Math.sin(t*bobSpeed)*.05;let sx=1,sy=1,sz=1;if(s==='listening'){const p=1+(.5+Math.sin(t*12)*.05)*.1;sx=p;sz=p;sy=1-(p-1)*.5}if(s==='speaking'){const p=1+(.3+Math.sin(t*8)*.2)*.14;sy=p;sx=1-(p-1)*.4;sz=sx}breathe.scale.set(sx,sy,sz);let tt=Math.sin(t*.5)*.03;if(s==='processing')tt=Math.sin(t*1.1)*.18;if(s==='error')tt=Math.sin(t*4)*.26;tilt.rotation.z=lerp(tilt.rotation.z,tt,.1);tilt.rotation.y=s==='processing'?Math.sin(t*.6)*.22:Math.sin(t*.3)*.05+mouse.x*.15;let lx=mouse.x*.12,ly=mouse.y*.1;if(s==='processing')lx+=Math.sin(t*1.2)*.04;if(s==='error')lx+=Math.sin(t*5)*.03;lx=Math.max(-.14,Math.min(.14,lx));ly=Math.max(-.1,Math.min(.1,ly));eyeL.position.x=lerp(eyeL.position.x,-.35+lx,.2);eyeR.position.x=lerp(eyeR.position.x,.35+lx,.2);eyeL.position.y=lerp(eyeL.position.y,.18+ly,.2);eyeR.position.y=lerp(eyeR.position.y,.18+ly,.2);
 if(blink<0&&t>nextBlink)blink=0;if(blink>=0){blink+=dt*9;const q=blink<1?1-blink:blink<2?blink-1:1;const openness=s==='error'?1.3:1;eyeL.scale.y=openness*q;eyeR.scale.y=openness*q;if(blink>=2){blink=-1;nextBlink=t+2+Math.random()*3}}browL.rotation.z=s==='error'?.4:s==='processing'?.15:-.05;browR.rotation.z=s==='error'?-.4:s==='processing'?-.2:.05;browL.position.y=browR.position.y=.42+(s==='listening'?.06:0)+ly*.5;if(s==='error'){mouth.scale.set(.7,1,1);mouth.rotation.z=Math.sin(t*3)*.35}else if(s==='speaking'){const q=(Math.sin(t*10)+1)*.5;mouth.scale.set(1+q*.4,1+q*3,1);mouth.rotation.z=0}else if(s==='processing'){mouth.scale.set(.8,.8,1);mouth.rotation.z=-.1}else{mouth.scale.set(1,1,1);mouth.rotation.z=0}pomGroup.rotation.z=Math.sin(t*2)*.06;beanie.rotation.z=Math.sin(t*2)*.02;const wave=Math.sin(t*1.5)*.05;armL.rotation.z=.15+wave;armR.rotation.z=-.15-wave;moteGroup.visible=s==='processing';moteGroup.rotation.y=t*1.6;renderer.render(scene,camera)};animate();const resize=()=>{const w=stage.clientWidth||1,h=stage.clientHeight||1;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)};addEventListener('resize',resize);return()=>{cancelAnimationFrame(raf);removeEventListener('mousemove',onMouse);removeEventListener('resize',resize);renderer.dispose();stage.removeChild(renderer.domElement)}},[]);
 return <div className="nova-stage" ref={mount}/>;
}
